version: '3.8'
services:
  backend:
    build:
      context: ./chat-app-backend
      dockerfile: Dockerfile
    ports:
      - "5232:5232"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5232

  frontend:
    build:
      context: ./chat-app
      dockerfile: Dockerfile
      args:
        NGINX_CONF: nginx.dev.conf
    ports:
      - "4200:80"
