name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.101'
    - name: Restore dependencies
      run: dotnet restore --project ./chat-app-backend
    - name: Build
      run: dotnet build --no-restore --project ./chat-app-backend
    - name: Test
      run: dotnet test --no-build --project ./chat-app-backend

  build-frontend:
    runs-on: ubuntu-latest
    needs: build-backend

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.0'
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Test
      run: npm test
      
  deploy:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Your AWS region
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REPOSITORY: your-ecr-repo-name
        IMAGE_TAG: latest
      run: |


      
